env:
  browser: true
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 6
  sourceType: module
rules:
  accessor-pairs: error
  array-bracket-spacing:
    - error
    - never
  array-callback-return: error
  arrow-body-style: error
  arrow-parens:
    - error
    - as-needed
  arrow-spacing:
    - error
    - after: true
      before: true
  block-scoped-var: error
  block-spacing: error
  brace-style:
    - error
    - stroustrup
  callback-return: error
  camelcase: error
  class-methods-use-this: 'off'
  comma-dangle:
    - error
    - always-multiline
  comma-spacing:
    - error
    - after: true
      before: false
  comma-style:
    - error
    - last
  complexity: error
  computed-property-spacing:
    - error
    - never
  consistent-return: error
  consistent-this: error
  curly:
    - error
    - multi-or-nest
  default-case: error
  dot-location:
    - error
    - property
  dot-notation:
    - error
    - allowKeywords: true
  eol-last: error
  eqeqeq: error
  func-call-spacing: error
  func-names: 'off' # TODO: discuss about activating this
  func-style:
    - error
    - declaration
    - allowArrowFunctions: true
  generator-star-spacing:
    - error
    - after
  global-require: 'off'
  guard-for-in: error
  handle-callback-err: error
  id-blacklist: error
  id-length: 'off'
  id-match: error
  indent:
    - error
    - 2
  init-declarations:
    - error
    - always
  jsx-quotes: error
  key-spacing: error
  keyword-spacing: error
  line-comment-position: 'off'
  linebreak-style:
    - error
    - unix
  lines-around-comment: error
  lines-around-directive: error
  max-depth: error
  max-len:
    - warn
    - code: 120
  max-lines: error
  max-nested-callbacks: error
  max-params:
    - error
    - 5
  max-statements:
    - error
    - 30
  max-statements-per-line: error
  multiline-ternary:
    - error
    - never
  new-cap: error
  new-parens: error
  newline-after-var: 'off'
  newline-before-return: 'off'
  newline-per-chained-call: 'off'
  no-alert: error
  no-array-constructor: error
  no-bitwise: error
  no-caller: error
  no-catch-shadow: error
  no-confusing-arrow: 'off'
  no-continue: 'off'
  no-console: 'off'
  no-div-regex: error
  no-duplicate-imports: error
  no-else-return: error
  no-empty:
    - error
    - allowEmptyCatch: true
  no-empty-function: error
  no-eq-null: error
  no-eval: error
  no-ex-assign: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-extra-parens: error
  no-floating-decimal: error
  no-global-assign: error
  no-implicit-globals: error
  no-implied-eval: error
  no-inline-comments: 'off'
  no-inner-declarations:
    - error
    - both
  no-invalid-this: 'off'
  no-iterator: error
  no-label-var: error
  no-labels: error
  no-lone-blocks: error
  no-lonely-if: error
  no-loop-func: error
  no-magic-numbers: 'off'
  no-mixed-operators: error
  no-mixed-requires: error
  no-multi-spaces: error
  no-multi-str: error
  no-multiple-empty-lines:
    - error
    - max: 1
  no-negated-condition: error
  no-nested-ternary: error
  no-new: error
  no-new-func: error
  no-new-object: error
  no-new-require: error
  no-new-wrappers: error
  no-octal-escape: error
  no-param-reassign: 'off' # TODO: discuss about activating this
  no-path-concat: error
  no-plusplus: error
  no-process-env: 'off'
  no-process-exit: 'off' # Probably needs to be activated when code is cleaned up for this
  no-proto: error
  no-prototype-builtins: error
  no-restricted-globals: error
  no-restricted-imports: error
  no-restricted-modules: error
  no-restricted-properties: error
  no-restricted-syntax: error
  no-return-assign: error
  no-script-url: error
  no-self-compare: error
  no-sequences: error
  no-shadow: 'off'
  no-shadow-restricted-names: error
  no-sync: 'off'
  no-tabs: error
  no-template-curly-in-string: error
  no-ternary: 'off'
  no-throw-literal: error
  no-trailing-spaces: error
  no-undef-init: error
  no-undefined: 'off'
  no-underscore-dangle: 'off'
  no-unmodified-loop-condition: error
  no-unneeded-ternary: error
  no-unsafe-negation: error
  no-unused-expressions: error
  no-unused-vars: warn
  no-use-before-define: error
  no-useless-call: error
  no-useless-computed-key: error
  no-useless-concat: error
  no-useless-constructor: error
  no-useless-escape: error
  no-useless-rename: error
  no-var: 'off' # discuss about this
  no-void: error
  no-warning-comments: warn
  no-whitespace-before-property: error
  no-with: error
  object-curly-newline: 'off'
  object-curly-spacing:
    - error
    - never
  object-property-newline:
    - error
    - allowMultiplePropertiesPerLine: true
  object-shorthand: 'off' # discuss about this
  one-var:
    - error
    - never
  one-var-declaration-per-line: error
  operator-assignment:
    - error
    - always
  operator-linebreak: error
  padded-blocks:
    - error
    - never
  prefer-arrow-callback: 'off' # discuss about this
  prefer-const: error
  prefer-numeric-literals: error
  prefer-reflect: 'off'
  prefer-rest-params: 'off'
  prefer-spread: error
  prefer-template: 'off' # discuss about this
  quote-props:
    - error
    - as-needed
  quotes:
    - error
    - single
  radix: error
  require-jsdoc: 'off'
  rest-spread-spacing:
    - error
    - never
  semi:
    - error
    - always # discuss about this
  semi-spacing:
    - error
    - after: false
      before: false
  sort-imports:
    - error
    - ignoreCase: true
  sort-keys: 'off' # discuss about this
  sort-vars: error
  space-before-blocks: error
  space-before-function-paren:
    - error
    - never
  space-in-parens:
    - error
    - never
  space-infix-ops: error
  space-unary-ops: error
  spaced-comment:
    - error
    - always
  strict: 'off'
  symbol-description: error
  template-curly-spacing:
    - error
    - never
  unicode-bom:
    - error
    - never
  valid-jsdoc: error
  vars-on-top: 'off'
  wrap-iife: error
  wrap-regex: error
  yield-star-spacing: error
  yoda: # discuss about this, deactivate, always, never ??
    - error
    - never
